services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hotel-small-system-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-small-system-prod
    ports:
      - "8080:80"
    restart: unless-stopped
